import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { buildDefine } from './scripts/buildInfo'

/**
 * Serve the dev server over https when `./scripts/dev-cert.sh` has been run.
 *
 * The in-app install button depends on `beforeinstallprompt`, which only fires
 * in a secure context. A phone opening http://<lan-ip>:5173 is not one, so the
 * service worker never registers and the button can never appear. Certificates
 * are per-machine and untracked, hence the file check rather than a flag: a
 * checkout without them still runs plain http.
 */
function devHttps() {
  const at = (f: string) => fileURLToPath(new URL(`./certs/${f}`, import.meta.url))
  const key = at('dev-key.pem')
  const cert = at('dev-cert.pem')
  if (!existsSync(key) || !existsSync(cert)) return undefined
  return { key: readFileSync(key), cert: readFileSync(cert) }
}

// Served from https://chiaretto.github.io/myonegym/ in production; root in dev.
export default defineConfig(({ command }) => {
  const base = command === 'build' ? '/myonegym/' : '/'

  return {
    base,
    // Version and build stamp for Settings -> "Atualizar app". Shared with
    // vitest.config.ts so the same globals exist in tests (see scripts/buildInfo).
    define: buildDefine(),
    // Expose the dev server on the LAN so the PWA can be opened from a phone.
    // Fixed port keeps the Windows portproxy → WSL forwarding rule valid.
    server: {
      host: true,
      port: 5173,
      strictPort: true,
      // Running the Windows-native node against the WSL share (\\wsl.localhost,
      // mapped to W:) puts the tree on a 9P network mount, which does not
      // implement ReadDirectoryChangesW — chokidar's fs.watch then dies with
      // EISDIR. Polling is the only watch mode that works there. Left off under
      // WSL/Linux, where native inotify is both correct and far cheaper.
      watch: process.platform === 'win32' ? { usePolling: true, interval: 300 } : undefined,
      https: devHttps(),
    },
    plugins: [
      react(),
      VitePWA({
        registerType: 'autoUpdate',
        // The app registers the service worker itself, from src/lib/appUpdate.ts:
        // it is the only way to hold the ServiceWorkerRegistration, and without
        // that handle nothing can call `update()` on demand. Leaving the
        // injected registerSW.js in place too would register the same worker
        // twice.
        injectRegister: null,
        includeAssets: ['favicon.ico', 'apple-touch-icon-180x180.png'],
        // The install prompt needs a service worker, and the app has an in-app
        // install screen that must be exercisable without deploying first.
        // Without this the SW only exists in the production build.
        devOptions: { enabled: true, suppressWarnings: true },
        manifest: {
          name: 'MyOneGym',
          short_name: 'MyOneGym',
          description:
            'Offline workout tracker — gyms, days, exercises and per-gym target weights.',
          lang: 'pt-BR',
          // Mirrors --surface-0 in src/styles/tokens.css. There is no shared source
          // of truth between CSS and the manifest, so this is a hand-kept copy —
          // as is the theme-color meta in index.html.
          theme_color: '#050607',
          background_color: '#050607',
          display: 'standalone',
          orientation: 'portrait',
          start_url: '.',
          // Stable app identity. Without it the browser derives the id from
          // start_url, so a future change to the served path would look like a
          // different app and strand the existing installation. Tracks `base`
          // because dev serves from the root and production from /myonegym/.
          id: base,
          // Generated by `npm run pwa-assets` from public/icon.png — see
          // pwa-assets.config.ts. Relative paths resolve against the manifest's
          // own URL, which is what keeps them right under the production base.
          //
          // Raster only: the brand master is a PNG (the handoff sheet had no
          // vector), so there is no SVG `any` entry to fall back on. Chrome uses
          // these for the home-screen shortcut and for the splash screen it
          // composes from name + background_color.
          icons: [
            { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {
              src: 'maskable-icon-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
          ],
        },
        workbox: {
          // webp is here for splash.webp: the boot splash has to paint on a
          // cold offline start too, and an unprecached background would leave
          // the launch covered by a flat dark rectangle.
          globPatterns: ['**/*.{js,css,html,svg,png,webp,ico,woff2}'],
          // iOS launch images are read by the OS at launch, not by the running
          // app, so precaching them only inflates the service worker manifest.
          // icon.png is the 1024px generator source, never requested at runtime.
          globIgnores: ['**/apple-splash-*.png', '**/icon.png'],
        },
      }),
    ],
  }
})
